name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main", "patch-1" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Theos
        uses: p0358/setup-theos@main

      - name: Build Package
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package FINALPACKAGE=1
        
      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: my-dylib-file
          path: "**/obj/**/*.dylib"
