name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main", "patch-1" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1

      - name: Build Package
        run: |
          # بناء المشروع كحزمة نهائية
          make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AntiReport-Dylib
          # التعديل هنا: سحب ملف الـ dylib من مجلد الـ .theos المخفي
          path: .theos/obj/debug/*.dylib

